In [1]:
"""
Softmax Regression?
Multinomial Classification : 세가지 이상으로 분류

ex) 점수에 따른 학점 분류

binary classifiaction 여러개로 구현한다.

A or not classifiation
B or not ,,
C or not ,,

[a1, a2, a3] X [[x1], [x2], [x3]] = Y1
[b1, b2, b3] X [[x1], [x2], [x3]] = Y2
[c1, c2, c3] X [[x1], [x2], [x3]] = Y3 

=>

[ [a1, a2, a3],
  [b1, b2, b3],
  [c1, c2, c3]] X [[x1], [x2], [x3]] => [[Y1], [Y2], [Y3]]

결과값이 행렬로 표현 된다고 할 때, 

이것을 소프트맥스 함수를 이용하여 각 결과값을 0과1사이 수치값(확률?)으로 계산한다. 
그 다음 가장 큰 값(가장 높은 확률)을 1로 나머지를 0으로 바꾼다.

예를들어 [[Y1], [Y2], [Y3]] => [[0.7], [0.2], [0.1]] => [[1], [0], [0]] 이다

hypothesis = tf.nn.softmax(tf.matmul(W, X))

"""

'\nSoftmax Regression?\nMultinomial Classification : 세가지 이상으로 분류\n\nex) 점수에 따른 학점 분류\n\nbinary classifiaction 여러개로 구현한다.\n\nA or not classifiation\nB or not ,,\nC or not ,,\n\n[a1, a2, a3] X [[x1], [x2], [x3]] = Y1\n[b1, b2, b3] X [[x1], [x2], [x3]] = Y2\n[c1, c2, c3] X [[x1], [x2], [x3]] = Y3 \n\n=>\n\n[ [a1, a2, a3],\n  [b1, b2, b3],\n  [c1, c2, c3]] X [[x1], [x2], [x3]] => [[Y1], [Y2], [Y3]]\n\n결과값이 행렬로 표현 된다고 할 때, \n\n이것을 소프트맥스 함수를 이용하여 각 결과값을 0과1사이 수치값(확률?)으로 계산한다. \n그 다음 가장 큰 값(가장 높은 확률)을 1로 나머지를 0으로 바꾼다.\n\n예를들어 [[Y1], [Y2], [Y3]] => [[0.7], [0.2], [0.1]] => [[1], [0], [0]] 이다\n\nhypothesis = tf.nn.softmax(tf.matmul(W, X))\n\n'

In [1]:
import tensorflow as tf
'''
변수 4개를 통해 나오는 1개 결과는 (0, 1, 2)세가지 중 하나. 
y_data 는 one-hot encoding 방식으로 표현된 결과 
'''
#data 
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
#y_data = [[2], [2], [2], [1], [1], [1], [0], [0]]
nb_classes = 3
#node
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, nb_classes])

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([1, nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
#cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, lables=y_data)
#cost = tf.reduce_mean(cost_i)
"""
과정
hypothesis를 실행했을 때 Nx3 행렬. y_data의 형태. axis=1 : 2차원 제거하면서 1차원에 합한다. 
Y * -log(hypothesis)는 가설이 올바를 때 0에 수렴. 
y_data가 one-hot형태이기 때문에 binary classification의 0과 1을 모두 확인할 수 있음. 
multi classification은 binary classification의 조합. 
"""
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cost_val, h_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})

        if step%200==0:
            print('step: {0}, hypothesis: {1}, cost: {2}'.format(step, h_val, cost_val))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
step: 0, hypothesis: [[9.86676335e-01 1.23126870e-02 1.01095403e-03]
 [9.72317934e-01 2.45906934e-02 3.09129152e-03]
 [7.02454209e-01 2.96048880e-01 1.49683410e-03]
 [8.52935433e-01 1.46693528e-01 3.70979396e-04]
 [9.99998212e-01 1.74975003e-06 1.76405609e-11]
 [9.84459043e-01 1.55306365e-02 1.02853146e-05]
 [9.99992967e-01 7.01054705e-06 9.22077553e-11]
 [9.99998808e-01 1.13884096e-06 2.08561141e-12]], cost: 4.815103530883789
step: 200, hypothesis: [[0.5777815  0.22801605 0.19420242]
 [0.11374126 0.16045448 0.7258042 ]
 [0.00865372 0.5774269  0.41391933]
 [0.00272191 0.3663601  0.63091797]
 [0.80322915 0.19490938 0.00186138]
 [0.04464673 0.80504566 0.15030761]
 [0.5577285  0.43422976 0.00804171]
 [0.55515355 0.44160143 0.00324505]], cost: 0.8587527871131897
step: 400, hypothesis: [[0.36023414 0.22637472 0.4133911 ]
 [0.09849668 0.15174888 0.7497544 ]
 [0.00877393 0.5

step: 4200, hypothesis: [[5.7507483e-03 2.9373126e-02 9.6487612e-01]
 [1.9067293e-02 1.4063007e-01 8.4030259e-01]
 [2.3760315e-04 3.5197717e-01 6.4778525e-01]
 [3.1145886e-04 6.9047767e-01 3.0921081e-01]
 [5.0269443e-01 4.6708417e-01 3.0221410e-02]
 [2.5508884e-01 7.4154454e-01 3.3666138e-03]
 [6.3943046e-01 3.5803351e-01 2.5360091e-03]
 [7.3371559e-01 2.6591545e-01 3.6896259e-04]], cost: 0.3539241552352905
step: 4400, hypothesis: [[5.0101443e-03 2.7544234e-02 9.6744567e-01]
 [1.8024577e-02 1.3996945e-01 8.4200597e-01]
 [2.0004324e-04 3.4576756e-01 6.5403241e-01]
 [2.7285414e-04 6.9535357e-01 3.0437356e-01]
 [4.9774915e-01 4.7272408e-01 2.9526863e-02]
 [2.5311360e-01 7.4379110e-01 3.0952352e-03]
 [6.4119828e-01 3.5647854e-01 2.3231145e-03]
 [7.3798555e-01 2.6168963e-01 3.2482666e-04]], cost: 0.3483104407787323
step: 4600, hypothesis: [[4.3770215e-03 2.5874278e-02 9.6974874e-01]
 [1.7064411e-02 1.3925849e-01 8.4367710e-01]
 [1.6886805e-04 3.3986294e-01 6.5996820e-01]
 [2.3965753e-04 7.0

step: 8200, hypothesis: [[5.4503302e-04 1.0226462e-02 9.8922849e-01]
 [7.6581882e-03 1.2248065e-01 8.6986119e-01]
 [1.1598477e-05 2.6608723e-01 7.3390120e-01]
 [3.2784075e-05 7.6090831e-01 2.3905888e-01]
 [4.1374025e-01 5.6497794e-01 2.1281879e-02]
 [2.1491362e-01 7.8415960e-01 9.2678313e-04]
 [6.7415935e-01 3.2520011e-01 6.4054196e-04]
 [8.0638587e-01 1.9356620e-01 4.7989022e-05]], cost: 0.26955848932266235
step: 8400, hypothesis: [[4.9277744e-04 9.7863292e-03 9.8972088e-01]
 [7.3818257e-03 1.2149495e-01 8.7112319e-01]
 [1.0169514e-05 2.6312494e-01 7.3686492e-01]
 [2.9810319e-05 7.6345503e-01 2.3651512e-01]
 [4.0989178e-01 5.6911361e-01 2.0994553e-02]
 [2.1304142e-01 7.8607780e-01 8.8078307e-04]
 [6.7582774e-01 3.2356602e-01 6.0621463e-04]
 [8.0935544e-01 1.9060038e-01 4.4155557e-05]], cost: 0.2664080858230591
step: 8600, hypothesis: [[4.4609228e-04 9.3705188e-03 9.9018341e-01]
 [7.1200095e-03 1.2051394e-01 8.7236601e-01]
 [8.9305186e-06 2.6024005e-01 7.3975104e-01]
 [2.7142545e-05 7.

In [13]:
import tensorflow as tf
import numpy as np
#for reproducibility
tf.set_random_seed(777)

xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot:", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape one_hot:", Y_one_hot)

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                                 labels=tf.stop_gradient([Y_one_hot])))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step%100==0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X:x_data, Y:y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss, acc))
    
    pred = sess.run(prediction, feed_dict={X:x_data})
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {}, True Y: {}".format(p == int(y), p, int(y)))


(101, 16) (101, 1)
Step:     0	Loss: 4.906	Acc: 9.90%
Step:   100	Loss: 0.605	Acc: 86.14%
Step:   200	Loss: 0.380	Acc: 88.12%
Step:   300	Loss: 0.281	Acc: 91.09%
Step:   400	Loss: 0.221	Acc: 93.07%
Step:   500	Loss: 0.181	Acc: 99.01%
Step:   600	Loss: 0.153	Acc: 100.00%
Step:   700	Loss: 0.132	Acc: 100.00%
Step:   800	Loss: 0.117	Acc: 100.00%
Step:   900	Loss: 0.105	Acc: 100.00%
Step:  1000	Loss: 0.095	Acc: 100.00%
Step:  1100	Loss: 0.087	Acc: 100.00%
Step:  1200	Loss: 0.080	Acc: 100.00%
Step:  1300	Loss: 0.074	Acc: 100.00%
Step:  1400	Loss: 0.069	Acc: 100.00%
Step:  1500	Loss: 0.065	Acc: 100.00%
Step:  1600	Loss: 0.061	Acc: 100.00%
Step:  1700	Loss: 0.058	Acc: 100.00%
Step:  1800	Loss: 0.055	Acc: 100.00%
Step:  1900	Loss: 0.052	Acc: 100.00%
[True] Prediction: 0, True Y: 0
[True] Prediction: 0, True Y: 0
[True] Prediction: 3, True Y: 3
[True] Prediction: 0, True Y: 0
[True] Prediction: 0, True Y: 0
[True] Prediction: 0, True Y: 0
[True] Prediction: 0, True Y: 0
[True] Prediction: 3, Tr