In [2]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
        


0 4.5209036 [[-0.1522719   0.25841275 -0.10985194]
 [-0.82770795  1.2653863   0.88883257]
 [ 0.82037187  0.6680439  -0.52767676]]
1 2.6745667 [[-0.12949483  0.1992255  -0.07344176]
 [-0.6699218   1.010014    0.9864188 ]
 [ 0.9749554   0.4273527  -0.4415691 ]]
2 1.6547667 [[-0.11861393  0.154661   -0.03975815]
 [-0.5397585   0.78979933  1.0764703 ]
 [ 1.0798575   0.24165128 -0.3607698 ]]
3 1.5748515 [[-0.12772699  0.14006472 -0.01604881]
 [-0.4840599   0.6918202   1.1187508 ]
 [ 1.0984772   0.18128045 -0.3190188 ]]
4 1.5429765 [[-0.1479043   0.14764266 -0.00344944]
 [-0.48582584  0.7154702   1.0968667 ]
 [ 1.059311    0.23275302 -0.33132523]]
5 1.5187304 [[-0.16140738  0.14435041  0.01334588]
 [-0.45338452  0.6790351   1.1008605 ]
 [ 1.0547304   0.2278223  -0.32181394]]
6 1.4968457 [[-0.17806767  0.14718972  0.02716687]
 [-0.43780234  0.6765661   1.0877473 ]
 [ 1.0334281   0.25399956 -0.3266888 ]]
7 1.4759337 [[-0.19281922  0.14657138  0.04253676]
 [-0.4128882   0.65507054  1.0843288 ]


86 0.80480516 [[-1.075258    0.12764592  0.9439009 ]
 [ 0.4162729   0.29309455  0.6171435 ]
 [ 0.5462887   0.6286231  -0.21417259]]
87 0.8019042 [[-1.0829746   0.12691844  0.9523449 ]
 [ 0.41954207  0.29387885  0.61309004]
 [ 0.5459813   0.6282266  -0.21346855]]
88 0.7990484 [[-1.0906373   0.12619677  0.96072936]
 [ 0.42274144  0.29468462  0.6090849 ]
 [ 0.54572433  0.62781125 -0.21279629]]
89 0.79623663 [[-1.0982473   0.12548122  0.96905494]
 [ 0.42587283  0.29551023  0.6051279 ]
 [ 0.5455162   0.62737876 -0.21215566]]
90 0.79346794 [[-1.1058053   0.12477199  0.97732216]
 [ 0.4289383   0.29635394  0.6012187 ]
 [ 0.5453555   0.62693036 -0.21154656]]
91 0.79074115 [[-1.1133121   0.12406933  0.9855317 ]
 [ 0.43193945  0.29721427  0.5973572 ]
 [ 0.5452406   0.6264675  -0.21096884]]
92 0.7880557 [[-1.1207687   0.12337343  0.9936841 ]
 [ 0.4348783   0.2980896   0.59354305]
 [ 0.5451703   0.62599134 -0.21042238]]
93 0.7854103 [[-1.1281756   0.12268453  1.00178   ]
 [ 0.43775627  0.2989787   

185 0.64049006 [[-1.6679459   0.09389346  1.5703409 ]
 [ 0.56315625  0.37017438  0.39318067]
 [ 0.6311135   0.58440214 -0.2547764 ]]
186 0.63951355 [[-1.6727781   0.09390712  1.5751594 ]
 [ 0.56371665  0.3706725   0.39212218]
 [ 0.63245904  0.5841089  -0.25582862]]
187 0.63854414 [[-1.6775954   0.09392611  1.5799576 ]
 [ 0.5642682   0.37116587  0.39107728]
 [ 0.6338072   0.5838178  -0.25688568]]
188 0.63758177 [[-1.6823976   0.09395038  1.5847356 ]
 [ 0.5648111   0.3716545   0.39004567]
 [ 0.63515806  0.58352876 -0.25794753]]
189 0.6366261 [[-1.6871852   0.09397989  1.5894936 ]
 [ 0.56534547  0.37213865  0.3890272 ]
 [ 0.6365113   0.58324194 -0.25901395]]
190 0.6356773 [[-1.6919581   0.09401454  1.5942318 ]
 [ 0.5658716   0.37261805  0.38802168]
 [ 0.63786715  0.5829569  -0.2600848 ]]
191 0.6347352 [[-1.6967164   0.09405436  1.5989504 ]
 [ 0.5663893   0.37309316  0.38702884]
 [ 0.6392252   0.5826741  -0.26116   ]]
192 0.63379973 [[-1.7014605   0.09409922  1.6036496 ]
 [ 0.5668991   0.3